<?php


/**
 * This class adds structure of 'sf_imaginable' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 10/07/09 06:04:09
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    plugins.sfImaginablePlugin.lib.model.map
 */
class sfImaginableMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.sfImaginablePlugin.lib.model.map.sfImaginableMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(sfImaginablePeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(sfImaginablePeer::TABLE_NAME);
		$tMap->setPhpName('sfImaginable');
		$tMap->setClassname('sfImaginable');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addColumn('POSITION', 'Position', 'INTEGER', true, null);

		$tMap->addColumn('OBJECT_CLASS', 'ObjectClass', 'VARCHAR', true, 100);

		$tMap->addColumn('OBJECT_ID', 'ObjectId', 'INTEGER', true, null);

		$tMap->addColumn('FILE_NAME', 'FileName', 'VARCHAR', true, 255);

		$tMap->addColumn('CAPTION', 'Caption', 'LONGVARCHAR', false, null);

	} // doBuild()

} // sfImaginableMapBuilder
