all:
  sfAssetsLibrary:
    upload_dir:               media

  sfImageTransformPlugin:
    default_adapter: GD # GD or ImageMagick
    mime_type:
      auto_detect: 1
      library: gd_mime_type # Fileinfo (PECL), MIME_Type (PEAR), GD Detection    
    
  sf_imaginable:
    thumbnail_crop:         true      
    thumbnail_large_width:  295
    thumbnail_large_height: 204
    thumbnail_small_width:  94
    thumbnail_small_height: 97
    file_size_limit:        3MB
    master_resize:          true
    master_width:           800
    master_height:          600

    #this one makes sure that the cache clearing process is executed after image upload
    save_object_after_image_upload: false   
    
    
  gallery2:
    dir:                 %SF_WEB_DIR%/gallery2
    uri:                 /gallery2/
    embed_uri:           /gallery
    login:               0
    login_redirect:      /login
    show_sidebar_blocks: 1
    map_mode:            3
    map_user:            user
    map_admin:           admin
    